# Project
version=26.1.1.0
group=dev.turtywurty.turtymultiloader
java_version=25
# Common
minecraft_version=26.1.1
mod_name=TurtyMultiloader
mod_author=TurtyWurty
mod_id=turtymultiloader
license=CC0-1.0
description=A Minecraft mod built for Fabric and NeoForge.
minecraft_version_range=[26.1.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.1-1
# Fabric: https://fabricmc.net/develop/
fabric_loader_version=0.18.6
fabric_api_version=0.145.2+26.1.1
fabric_gametest_api_version=4.0.13+00a1fba645
energy_api_version=5.0.0
# NeoForge: https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.1.1-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
