pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = uri('https://maven.fabricmc.net')
                }
            }
            filter {
                includeGroupAndSubgroups('net.fabricmc')
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'TurtyMultiloader'

include('common')
include('fabric')
include('neoforge')
include('gas-common')
project(':gas-common').projectDir = file('modules/gas/common')
include('gas-fabric')
project(':gas-fabric').projectDir = file('modules/gas/fabric')
include('gas-neoforge')
project(':gas-neoforge').projectDir = file('modules/gas/neoforge')
include('slurry-common')
project(':slurry-common').projectDir = file('modules/slurry/common')
include('slurry-fabric')
project(':slurry-fabric').projectDir = file('modules/slurry/fabric')
include('slurry-neoforge')
project(':slurry-neoforge').projectDir = file('modules/slurry/neoforge')
include('multiblock-common')
project(':multiblock-common').projectDir = file('modules/multiblock/common')
include('multiblock-fabric')
project(':multiblock-fabric').projectDir = file('modules/multiblock/fabric')
include('multiblock-neoforge')
project(':multiblock-neoforge').projectDir = file('modules/multiblock/neoforge')
include('testmod-fabric')
project(':testmod-fabric').projectDir = file('testmod/fabric')
include('testmod-neoforge')
project(':testmod-neoforge').projectDir = file('testmod/neoforge')
