modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "CC0-1.0"

[[mods]]
modId = "turtymultiloader_testmod"
version = "${version}"
displayName = "TurtyMultiloader Test Mod"
description = '''Development-only integration and GameTest coverage for TurtyMultiloader.'''

[[dependencies.turtymultiloader_testmod]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.turtymultiloader_testmod]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.turtymultiloader_testmod]]
modId = "turtymultiloader"
type = "required"
versionRange = "[${version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.turtymultiloader_testmod]]
modId = "gasapi"
type = "required"
versionRange = "[${version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.turtymultiloader_testmod]]
modId = "slurryapi"
type = "required"
versionRange = "[${version},)"
ordering = "AFTER"
side = "BOTH"
